#!/usr/bin/env python3
"""Opt-in PostgreSQL 17 non-superuser regression; all SQL changes are rolled back."""
import argparse
import importlib.util
import os
import pathlib
import re
import subprocess


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--execute-postgres-regression',action='store_true')
    args=parser.parse_args()
    if not args.execute_postgres_regression:
        print('SKIP: explicit disposable PostgreSQL regression execution required')
        return 0
    database=os.environ.get('PGDATABASE','')
    username=os.environ.get('PGUSER','')
    if not re.fullmatch(r'bootstrap_regression_[a-z0-9_]+',database) or not re.fullmatch(r'[a-z][a-z0-9_]{0,15}',username) or os.environ.get('PGSERVICE'):
        print('PENDING: explicit disposable PGDATABASE and NOSUPERUSER PGUSER required')
        return 2
    spec=importlib.util.spec_from_file_location('bootstrap',pathlib.Path(__file__).resolve().parents[1]/'scripts/lib/rds-bootstrap.py')
    bootstrap=importlib.util.module_from_spec(spec);spec.loader.exec_module(bootstrap)
    generated=bootstrap.bootstrap_sql({'databaseName':database,'masterUsername':username},
                                     {'database':'LOCAL_TEST_ONLY_runtime','migration':'LOCAL_TEST_ONLY_migration'})
    assert generated.startswith('BEGIN;\n') and generated.endswith('COMMIT;\n')
    body=generated.removeprefix('BEGIN;\n').removesuffix('COMMIT;\n')
    preflight=f"""BEGIN;
DO $check$ BEGIN
IF current_setting('server_version_num')::int NOT BETWEEN 170000 AND 179999
 OR current_database() <> '{database}' OR current_user <> '{username}'
 OR NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname=current_user AND NOT rolsuper AND rolcreaterole AND rolcreatedb)
 OR NOT EXISTS (SELECT 1 FROM pg_database WHERE datname=current_database() AND datdba=(SELECT oid FROM pg_roles WHERE rolname=current_user))
 OR EXISTS (SELECT 1 FROM pg_roles WHERE rolname IN ('commerce_runtime','commerce_migration'))
THEN RAISE EXCEPTION 'Disposable PostgreSQL 17 owner and absent application roles required'; END IF;
END $check$;
"""
    migration=f"""GRANT commerce_migration TO "{username}" WITH SET TRUE;
SET LOCAL ROLE commerce_migration;
CREATE TABLE public.products (id bigint);
CREATE TABLE public.inventory (id bigint);
CREATE TABLE public.orders (id bigint GENERATED BY DEFAULT AS IDENTITY);
CREATE TABLE public.order_items (id bigint GENERATED BY DEFAULT AS IDENTITY);
CREATE TABLE public.migration_ledger (id bigint);
RESET ROLE;
GRANT commerce_migration TO "{username}" WITH SET FALSE;
"""
    checks="""DO $check$ BEGIN
IF (SELECT nspowner FROM pg_namespace WHERE nspname='public') <> 'commerce_migration'::regrole
 OR has_database_privilege('commerce_migration',current_database(),'CREATE')
 OR has_schema_privilege('commerce_runtime','public','CREATE')
 OR NOT has_table_privilege('commerce_runtime','public.products','SELECT')
 OR has_table_privilege('commerce_runtime','public.products','INSERT')
 OR NOT has_table_privilege('commerce_runtime','public.inventory','UPDATE')
 OR NOT has_table_privilege('commerce_runtime','public.orders','INSERT')
 OR has_table_privilege('commerce_runtime','public.orders','DELETE')
 OR has_table_privilege('commerce_runtime','public.migration_ledger','SELECT')
 OR NOT has_table_privilege(current_user,'public.orders','SELECT')
 OR NOT has_sequence_privilege('commerce_runtime','public.orders_id_seq','USAGE')
 OR EXISTS (SELECT 1 FROM pg_roles WHERE rolname IN ('commerce_runtime','commerce_migration') AND
   (rolsuper OR rolcreatedb OR rolcreaterole OR rolreplication OR rolbypassrls OR rolinherit))
 OR (SELECT count(*) FROM pg_auth_members WHERE member=(SELECT oid FROM pg_roles WHERE rolname=current_user)
   AND roleid IN ('commerce_runtime'::regrole,'commerce_migration'::regrole)
   AND admin_option AND NOT inherit_option AND NOT set_option) <> 2
THEN RAISE EXCEPTION 'Non-superuser bootstrap privilege regression'; END IF;
END $check$;
ROLLBACK;
"""
    result=subprocess.run(['psql','-X','--no-password','--set=ON_ERROR_STOP=1'],
                          input=preflight+body+migration+body+checks,text=True,capture_output=True,timeout=60)
    if result.returncode:
        print('PENDING: non-superuser PostgreSQL regression failed; diagnostics suppressed')
        return 2
    print('POSTGRES_REGRESSION_VERIFIED: fresh and repeated non-superuser bootstrap rolled back')
    return 0


if __name__=='__main__': raise SystemExit(main())
